var target = "n00dles";
print("Target: " + target);

var moneyThresh = getServerMaxMoney(target) * 0.75;
print("Money threshhold: " + moneyThresh);

var securityThresh = getServerMinSecurityLevel(target) + 5;
print("Security threshhold: " + securityThresh);

while(true) {
    if (getServerSecurityLevel(target) > securityThresh) {
        weaken(target);
    } else if (getServerMoneyAvailable(target) < moneyThresh) {
        grow(target);
    } else {
        hack(target);
    }
}
